Pocket/collection-api

.circleci/config.yml, schema-admin.graphql
as `apollo service:check` is now deprecated, use the suggested `rover` package instead.
copied off of @kschelonka's ~~paper~~ [PR](https://github.com/Pocket/list-api/pull/184/files).
=> fix(apollo service check): use rover for subgraph check/deploy

schema-admin.graphql, src/database/mutations/CollectionStory.integration.ts, src/database/queries/CollectionStory.integration.ts, src/database/types.ts, src/test/helpers.ts
Add the new `fromPartner` field to `createCollectionStory` and `updateCollectionStory` mutations so that they can be used by the frontend. 
Note that since the new field/variable is required in these mutations this PR will break the Admin UI if merged before the rest of the frontend changes are merged.
=> [BACK-755] Add 'fromPartner' field to create/update story mutation input types

schema-admin.graphql
As discussed here: https://github.com/Pocket/collection-api/pull/327, leave the `getCollectionPartnerAssociation` query in place as it's used in integration tests instead of deleting it and update schema comments for queries used in tests only.
=> [BACK-755] Update schema comments for queries used in tests only

src/database/mutations/CollectionPartnerAssociation.integration.ts, src/database/mutations/CollectionPartnerAssociation.ts
Make sure client apps never show a story as 'sponsored' in a non-sponsored collection.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-988
- The 'deleteCollectionPartnerAssociation' mutation now looks for all sponsored stories
in the related collection and updates the 'fromPartner' flag to 'false' for those.
- Added an extra integration test.
=> [BACK-988] Uncheck 'fromPartner' flag on sponsored stories on deleting a partnership

prisma/migrations/20210823001422_add_review_status_to_collections/migration.sql, prisma/schema.prisma, prisma/seed.ts, schema-shared.graphql, src/database/queries/Collection.integration.ts, src/database/queries/Collection.ts
Allow the curators to preview collections exactly as they are going to appear live without publishing them first. 
Tickets:
- https://getpocket.atlassian.net/browse/BACK-986
- Added a 'REVIEW' status for collections so that they can be previewed live. Added a Prisma migration to add this status to the database schema.
- Amended the 'getCollectionBySlug' query to include collections with the 'REVIEW' status in the results. Did not make any changes to 'getCollectionsBySlug' query.
- Updated integration tests.
- Added two more collections with the new 'REVIEW' status to the seed script.
=> [BACK-986] Add 'REVIEW' status and allow it in 'getCollectionBySlug' query.

src/test/admin-server/mutations/CollectionPartner.server.integration.ts, src/test/admin-server/mutations/mutations.gql.ts, src/test/admin-server/queries/CollectionPartner.server.integration.ts, src/test/admin-server/queries/queries.gql.ts
Chip away at server integration tests one entity at a time.
Added tests for queries and mutations that are used by Curation Tools Frontend.
=> chore(tests): Add server integration tests for CollectionPartner

src/test/helpers.ts
This is a small tweak that is almost frivolous but it has long bugged me that in the seed data we only supply some entities with images and not others (i.e. collection stories, but not collections), and that the images that were there had the same URL, so a list of stories all sported the same image in a list.
=> chore(local dev): Add randomised images to all entities in seed script

.aws/src/config/index.ts, .aws/src/main.ts
Make sure we don't deploy alarms we never needed to have in the first place.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1061
=> [BACK-1061] Make sure no PagerDuty services are created for Dev environment

src/middleware/prisma.spec.ts, src/middleware/prisma.ts
apollo studio is showing many 500 errors in collections around the `getCollectionBySlug` query. found an bug in the middleware (where we modify prisma results to link to parser items) that didn't handle empty results from any prisma-based `find` operation.
this should unblock us on implementing the `http5xxError` alarm.
not sure if this link to apollo studio works, but here's a try: https://studio.apollographql.com/graph/pocket-client-api/operations?query=78504a2206a698b9ecada3d5d0b9f15a816e667e&queryName=GetCollectionBySlug&tab=traces&trace=pocket-client-api~2021%3A09%3A15~4d778cfec62f01bba8e14242d7d5d85ed93e732b697628b164fca0403f782cdd&traceBucket&variant=current
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1055
=> fix(middleware): handle no find results in middleware

.aws/package.json, .aws/src/config/index.ts, .aws/src/main.ts
configure & enable http5xx alarm
- add `isDev` config variable
- update to latest terraform-modules
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1057
going with our (now) standard 25% 5xx over 4 datapoints in 20 minutes config.
=> fix(alarms): configure & enable http5xx alarm

src/dataLoaders/collectionLoader.spec.ts, src/dataLoaders/collectionLoader.ts
ensures that collections requested by parser items are returned in the order requested.
this fixes a dataloader issue where client api would request multiple collections based on slug to satisfy parser item `collection` properties and those collections would be returned out of order, resulting in mismatched item data.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1217
added a sorting algorithm before returning the collections, based on [a generic sorter in apollo utils](https://github.com/Pocket/apollo-utils/blob/890862f2b66b8179e706a1522ce8d07da67a7c94/src/dataloader.ts#L109).
=> fix(getCollectionsBySlugs): return collections in requested order

src/admin/context.ts, src/admin/resolvers/mutations.ts, src/admin/resolvers/queries.ts, src/shared/constants.ts, src/test/admin-server/queries/CollectionAuthor.server.integration.ts, src/test/admin-server/queries/CollectionPartner.server.integration.ts, src/test/admin-server/queries/CurationCategory.server.integration.ts, src/test/admin-server/queries/IABCategory.server.integration.ts, src/test/admin-server/queries/Language.server.integration.ts
add authorization to admin queries.
What changed:
- update `authenticatedUser` context
- add a bunch of missing `await`s
- update server integration tests for queries
- remove `console.log` from mutation helper
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1310
updating all existing server integration tests, but not feeling great about how many are missing - `Collection`, `CollectionStory`, and `CollectionPartnerAssociation`. do we feel comfortable merging this with those tests missing?
i am not totally comfortable building upon this level of tech debt - particularly given the number of `await` statements that were previously missing and added in this PR. if anything, i would want to ship this on a monday (or tuesday next week given the holiday) rather than push it out before a …
=> feat(auth): add authentication to all admin queries

src/public/resolvers/index.ts, src/public/resolvers/queries/Collection.integration.ts, src/public/resolvers/queries/Collection.ts, src/public/resolvers/queries/sample-queries.gql.ts, src/shared/fragments.gql.ts, src/test/public-server.ts
begin improving/standardizing integration tests
- add public test server
- add graphql fragments file
- move public query resolvers into a directory
- add a single basic integration test for public collection query
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1317
=> chore(tests): begin improving/standardizing integration tests

schema-public.graphql, src/public/resolvers/index.ts, src/public/resolvers/queries/Collection.integration.ts, src/public/resolvers/queries/sample-queries.gql.ts
Remove the verb from the `collectionBySlug` query
I specifically chose not to rename the getCollections query because I figured when we do that we should also make the new `collections` query use Cursor Based pagination.
I also did not touch the admin queries since the backend team only uses those and there's a lot to change there.
=> fix(verbs): removing verb from the collectionBySlug query

prisma/migrations/20221101154706_refactor_collection_label_table_add_associations/migration.sql, prisma/migrations/20221102191937_refactor_label_table_remove_index_on_primary_key/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/database/types.ts, src/test/helpers.ts
Follow up PR to https://github.com/Pocket/collection-api/pull/996.
We missed the two table associations to `Collection` and `Label` table. Also adding a composite key and a `createdAt` column. 
Tickets:
- BACK-1653
=> fix(CollectionLabel table): [BACK-1653] Refactor table to add collection and label associations

schema-admin.graphql, src/admin/resolvers/index.ts, src/admin/resolvers/queries/Label.auth.integration.ts, src/admin/resolvers/queries/Label.integration.ts, src/admin/resolvers/queries/Label.ts, src/admin/resolvers/queries/sample-queries.gql.ts, src/database/queries/Label.ts, src/database/types.ts, src/test/helpers.ts
Add a new `labels` query so that the frontend can, in future, retrieve all available labels.
- Added a `labels` query to admin schema and a corresponding resolver.
- Added integration tests.
- Added authentication-related tests.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1637
=> feat(labels): [BACK-1637] Admin schema - add a `labels` query and resolver

prisma/schema.prisma, schema-admin.graphql, src/admin/resolvers/index.ts, src/admin/resolvers/mutations.ts, src/admin/resolvers/mutations/Collection.integration.ts, src/database/mutations/Collection.ts, src/database/types.ts, src/public/resolvers/index.ts, src/shared/fragments.gql.ts, src/shared/resolvers/types.ts
The goal of this PR is to be able to create a collection and assign one or more labels to it at the same time.
- Updated admin schema to add label external ids to mutation input.
- Updated DB-level resolver to add existing labels to a collection and retrieve them as part of mutation response.
- Added custom resolvers both for public and private schemas for the Label entity - there is no easier way to get the label data out when retrieved as part of Collection.
- Updated mutations to take in authenticated user from server context so that we can record who attached a label to a collection.
- Added integration tests.
- https://getpocket.atlassian.net/browse/BACK-1641
- https://getpocket.atlassian.net/browse/BACK-1650
=> feat(labels): [BACK-1641, BACK-1650] Update `createCollection` mutation to incorporate labels

prisma/migrations/20221107035551_populate_label_table/migration.sql, prisma/seed.ts
The goal of this PR is to have the first label data in the database for use on the frontend. 
- Added a Prisma migration to add the first label to the database.
- Updated the seed script to tweak one of the seed label values so that there is no conflict on running it with the migration already applied.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1674
=> feat(labels): [BACK-1674] Populate the `Label` table

schema-admin.graphql, src/admin/context.ts, src/admin/resolvers/mutations/Collection.integration.ts, src/database/mutations/Collection.ts, src/database/types.ts, src/shared/resolvers/types.ts
Allow the curators to add to or remove labels from existing collections.
-  Updated admin schema to add label external ids to mutation input.
- Updated DB-level resolver to add or replace existing labels to a collection and retrieve them as part of mutation response.
- Added integration tests.
- Added more explanatory comments to custom resolvers for label fields introduced in #1000.
Tickets:
- https://getpocket.atlassian.net/browse/BACK-1651
- https://getpocket.atlassian.net/browse/BACK-1639
=> feat(labels): [BACK-1651, BACK-1639] Update `updateCollection` mutation to incorporate labels

schema-public.graphql, src/admin/resolvers/queries/Collection.integration.ts, src/admin/resolvers/queries/Collection.ts, src/dataLoaders/collectionLoader.integration.ts, src/database/queries/Collection.ts, src/public/resolvers/queries/Collection.integration.ts
Return label data with all collection-related queries; we overlooked some in the initial stage of updates to Collection API.
https://getpocket.atlassian.net/browse/BACK-1685
=> fix(labels): [BACK-1685] Return labels for individual collection queries

schema-admin.graphql, src/admin/resolvers/index.ts, src/admin/resolvers/mutations.ts, src/admin/resolvers/mutations/Label.integration.ts, src/admin/resolvers/mutations/sample-mutations.gql.ts, src/admin/resolvers/queries/Label.integration.ts, src/database/mutations.ts, src/database/mutations/Label.ts
- Added database & resolver mutation to createLabel.
- Checking for label name uniqueness.
- Added appropriate integration tests.
Tickets:
- [https://getpocket.atlassian.net/browse/BACK-1638](https://getpocket.atlassian.net/browse/BACK-1638)
=> BACK-1638: createLabel mutation 

src/admin/resolvers/mutations/Collection.integration.ts, src/config/index.ts, src/database/mutations/Collection.ts, src/database/utils.ts
Currently, a collection can have a max of 20 labels. Add this limit to `createCollection` and `updateCollection` mutations.
* [https://getpocket.atlassian.net/browse/INFRA-935](https://getpocket.atlassian.net/browse/INFRA-935)
* Added a `collectionLabelLimit` config variable to `src/config` to store the collection-label association limit which can be easily updated in the future if needed.
* Added a `checkCollectionLabelLimit(labelExternalIds: string[])` to `src/database/utils.ts` utility function to check the limit.
=> INFRA-935: Add a limit to collection-label association

schema-shared.graphql, src/public/resolvers/index.ts, src/public/resolvers/queries/Collection.integration.ts, src/public/resolvers/queries/Collection.ts, src/test/helpers.ts
Allow federated graphs to return collections by slug. See the [parent PR for more context](https://github.com/Pocket/curated-corpus-api/pull/829)
- https://github.com/Pocket/curated-corpus-api/pull/829
Tried to follow all existing patterns.
=>  Collection resolve by slug reference

.github/PULL_REQUEST_TEMPLATE.md, schema-admin.graphql, src/admin/resolvers/index.ts, src/admin/resolvers/mutations.ts, src/admin/resolvers/mutations/Label.auth.integration.ts, src/admin/resolvers/mutations/Label.integration.ts, src/admin/resolvers/mutations/sample-mutations.gql.ts, src/database/mutations.ts, src/database/mutations/Label.ts, src/database/types.ts, src/shared/constants.ts
* Add the `updateLabel` mutation to allow curators to update label names, but prevent updating labels that are already attached to collections.
* Add relative tests.
* Also update one small thing in the PR template.
- [https://getpocket.atlassian.net/browse/INFRA-936](https://getpocket.atlassian.net/browse/INFRA-936)
=> INFRA-936: add updateLabel mutation and tests

.aws/.gitignore, .aws/src/files/nodejs/node_modules/synthetic.ts, .aws/src/main.ts, .aws/src/monitoring.ts, .aws/tsconfig.json, README.md
Recent collection-api incident highlighted that existing monitoring was not alerting when collection sites were all 'down' (in this case, all returning 404).
This PR adds an AWS Cloudwatch-based Synthetic Canary which check https://getpocket.com/collections/pocket-best-of-2022-collections every 5 minutes, and if it gets lower than 66% success rate in a 15 minute period (success being the site returns a 2xx), it will alert Pagerduty.
This is setup to only be implemented for production.
- Link to docs
[- Link to JIRA tickets](https://getpocket.atlassian.net/browse/INFRA-1082)
Using Cloudwatch Synthetic Checks instead of New Relic since the Backend Team doesn't currently have access to New Relic, and it would suck to be paged for an alert you can't access.
=> fix(uptime check): add uptime check to alert if popular collections site is not returning 2xx

README.md
Update the docs so that instructions for something that is rarely needed in practice don't get lost.
- unticketed. Related to the recent need to reseed the data on Dev for Shareable Lists API.
=> chore(docs): Add link to instructions for resetting the Dev environment

src/public/server.ts
Enable variable and error messages in studio
The issue:
Verifying that query params all look safe
=> Enable variable and error messages in studio

package.json
Removing duplicate `@pocket-tools/...` package declaration
=> fix(pocketTools): Remove duplicate pocket tools package declaration

.circleci/config.yml
Stop using deprecated CircleCI images - the newer ones were introduced in 2020: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
https://getpocket.atlassian.net/browse/INFRA-1364
=> chore(circleci): [INFRA-1364] Update CircleCI images from deprecated to current `cimg/node` ones

.aws/src/main.ts
Remove this service from Tier 1 PagerDuty policy.
One alarm was downgraded from critical to a non-critical one.
JIRA ticket:
* https://mozilla-hub.atlassian.net/browse/SOCIALPLAT-700
=> chore(pagerduty):  [SOCIALPLAT-700] Remove this service from Tier 1 PagerDuty

.aws/src/main.ts
Prospects were not generated in the last 2 days, because collection hydration failed.
Handle spikes in requests better, to prevent spikes in latency and 5xx error rate.
- [Incident doc](https://docs.google.com/document/d/1mMtP0337OqJBXEu-RkvzoH-O8YabErH9BycR1fZdvyc/edit)
- [Incident Slack thread](https://mozilla.slack.com/archives/C05EAHBM35Z/p1698683597264689)
- Increase memory from 2GB to 8GB, because _average_ memory was often above 50% during the incident, with spikes up to 90%.
- Increase from .5 vCPU to 1 vCPU
- Increase stepScaleOutAdjustment from 2 to 4, to be able to scale out faster when there is sustained higher load.
- Increase maximum number of tasks to 20. Probably not necessary with the above changes, but the service was not able to handle the load at 10 tasks.
=> feat: more and bigger tasks, with faster scale-out

.prettierrc.json, package-lock.json, prisma/seed.ts, src/database/client.ts, src/events/events.spec.ts, src/events/events.ts, src/express.ts, src/main.ts, src/public/resolvers/item.ts, src/utils.ts
in a long [slack thread](https://mozilla.slack.com/archives/C05EVRU1U1X/p1705001200188929), we have reason to believe ts-logger is causing memory leak issues - specifically on services that do not deploy (task roll-over) very often.
this PR is to check/validate that hypothesis. if this PR results in better memory metrics, we'll need to follow-up in a somewhat significant way in two aspects: meaningful, discoverable logging and updating other services using ts-logger.
- https://mozilla-hub.atlassian.net/browse/MC-445
=> perf(ts-logger): remove ts-logger to attempt to mitigate memory issues

src/utils.ts
removing a superfluous logging statement that provides no value. hoping this reduces some CPU usage (as this logging statement is hit in high volume).
- https://mozilla-hub.atlassian.net/browse/MC-450
=> perf(logging): remove logging when URL isn't a collection

prisma/migrations/20240119192017_add_status_language_published_at_compound_index_collections/migration.sql, prisma/schema.prisma
add a compound index to increase performance on the `getCollections` public query.
[successful dev deploy](https://app.circleci.com/pipelines/github/Pocket/collection-api/6601/workflows/756026a7-8fcc-49c5-9e0a-82095add8a04).
- https://mozilla-hub.atlassian.net/browse/MC-501
see the ticket above for details, but tl;dr - the query _always_ includes a `language` and `status` filter in the `WHERE` clause, and is _always_ ordered by `publishedAt`. we've tested this migration and index on dev.
=> perf: add compound index to Collection model for public getCollections query
